# Generated by Django 5.0.1 on 2024-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_face',
            field=models.ImageField(null=True, upload_to='image', verbose_name='تصویر'),
        ),
    ]
