# Generated by Django 5.0.1 on 2024-02-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='cat_books', to='blog.category', verbose_name='دسته بندی '),
        ),
    ]
