# Generated by Django 5.0.1 on 2024-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Ip_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_ip_user', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ip_user',
            field=models.ManyToManyField(blank=True, related_name='ip_user', to='blog.get_ip_address'),
        ),
    ]
