# Generated by Django 5.0.1 on 2024-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_get_ip_address_book_ip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer_book',
            field=models.CharField(max_length=100, null=True, verbose_name='نویسنده ی کتاب'),
        ),
    ]
